server:
  port: 8080

spring:
  datasource:
    name: sample_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/airline-ticket-management-system
    username: root
    password: vamsi
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: EST





logging:
  level:
    org:
      springframework: DEBUG